import { KadenceTabsHydrator } from "./kadence-tabs-hydrator";
import { SplideHydrator } from "./splide-hydrator";
import { MobileDrawerHydrator } from "./mobile-drawer-hydrator";
import { GetwidAccordionHydrator } from "./getwid-accordion-hydrator";

/**
 * Renders a mirrored WordPress page (generated by scripts/mirror.mjs) as a
 * near-pixel-perfect clone: page-specific inline CSS in a <style> tag and the
 * original body markup via dangerouslySetInnerHTML. Shared theme/plugin CSS
 * (identical across pages) is NOT included here — it's imported once via
 * src/legacy/base.css in the (public) layout.
 *
 * The original <body> classes are placed on the wrapping <div> so Kadence's
 * ancestor selectors (e.g. `.transparent-header #masthead`) still match. This
 * is a temporary scaffold — sections get replaced with real React over time.
 *
 * KadenceTabsHydrator restores click-to-switch behavior for Kadence Tabs
 * blocks, SplideHydrator restores real carousel behavior for Splide sliders,
 * and MobileDrawerHydrator restores the hamburger menu — all JS-driven and
 * stripped along with every other WordPress script.
 */
export function LegacyPage({
  css,
  html,
  bodyClass,
}: {
  css: string;
  html: string;
  bodyClass: string;
}) {
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: css }} />
      <div className={bodyClass} dangerouslySetInnerHTML={{ __html: html }} />
      <KadenceTabsHydrator />
      <SplideHydrator />
      <MobileDrawerHydrator />
      <GetwidAccordionHydrator />
    </>
  );
}
