// Real testimonials extracted verbatim from the legacy site: the 3 that
// were on the homepage carousel (src/legacy/home.ts, a Kadence Testimonials
// block) plus all 19 from the full /opinie page grid (src/legacy/opinie.ts).
// Used by TestimonialsCarousel (src/components/clauwi/testimonials-carousel.tsx).
export type Testimonial = { name: string; title: string; content: string };

export const TESTIMONIALS: Testimonial[] = [
  { name: "Beata Własny", title: "Wspaniały kurs!", content: "Kurs dla doradców prowadzony przez Izę trenerkę Clauwi jest wspaniały: pełen intensywnych ćwiczeń, analizy sytuacji codziennych spotykanych przez doradców oraz dużej ilości wiedzy o ciele człowieka i zdrowym rozwoju dzieci." },
  { name: "Anna Pożarlik", title: "Fantastyczny kurs", content: "Szkolenie prowadzone przez Izę otworzyło mi oczy i umysł na całą istotę noszenia. Zrozumiałam i poczułam na sobie pozycję dziecka, poznałam triki, które ulepszyły mój system wiązania ale i zmieniłam myślenie o samej szkole i jej podejściu do rodziców i noszących. Jednym słowem, Iza, zmieniłaś moje życie na lepsze 😀" },
  { name: "Zuzanna Wasiukiewicz-Balkowska", title: "Szkolenie na najwyższym poziomie.", content: "Instruktorka zawsze pomocna, nawet po zakończeniu szkolenia. Kurs obejmował wszystkie zagadnienia, które mnie interesują. Teraz z niecierpliwością czekam na możliwość kontynuacji i zdobywania nowej wiedzy." },
  { name: "Adriana Stąpor (kurs I 2017)", title: "Idealne proporcje", content: "Wybierając się na kurs, obawiałam się, że to będzie takie trochę “pitu pitu” , jakie to chusty są fajne… A tu niespodzianka – bardzo wysoki poziom merytoryczny i organizacyjny, idealne proporcje między wiedzą teoretyczną, a praktycznymi ćwiczeniami, świetnie opracowane materiały szkoleniowe, no i imponujące zaplecze chustowo-nosidłowe! Byłam pod ogromnym wrażeniem tego, jak można wykazać maksimum elastyczności wobec uczestniczek, które są też młodymi mamami, jednocześnie zachowując pełen profesjonalizm szkolenia. Wysokie wymagania wobec przyszłych doradców, którzy swoimi nazwiskami mają reprezentować ClauWi, a jednocześnie świetna, przyjacielska wręcz atmosfera spotkania." },
  { name: "Aleksandra Gabor", title: "Nieocenione wsparcie poszkoleniowe", content: "Uczyłam się od ClauWianki i sama zapragnęłam nią zostać. Szkolenia tej szkoły to nie tylko technika, ale i budowanie kompetencji społecznych. Cudowna atmosfera i nieocenione wsparcie poszkoleniowe." },
  { name: "Diana Wiśniowska-Krawczyk (kurs XI2016)", title: "Cierpliwe tłumaczenie", content: "Jako mama, która w temacie noszenia przeszła przez etap błądzenia, takie osoby jak Iza są jak światełko w tunelu. Poprzez cierpliwe omawianie zagadnień dotyczących noszenia, tłumaczenie filozofii i aspektów z noszeniem związanych oraz okraszanie tego poczuciem humoru, który rozładuje każde napięcie i stres związany z wiązaniem nawet te najmniej doświadczone mamy, Iza pełni rolę doskonałego przewodnika i nauczyciela. Motywuje, zachęca. Kurs prowadzony przez szkołę ClauWi otwiera oczy na to, co daje taka bliskość. Jak bliskość, która jest motana w prawidłowy sposób, może pomóc nie tylko dziecku ale również rodzicom. To godziny praktyki, potu i łez ale również ogromnej satysfakcji z tego, co można poprzez to osiągnąć" },
  { name: "Dobrochna Moździerz (kursXI2016)", title: "Wiedza i doświadczenie", content: "Wiedza i doświadczenie trenerki – Izy – nie do przecenienia. Bardzo mądra kobieta, dzięki której, przy odrobinie dobrej woli i otwartego umysłu odbiorcy, można dowiedzieć się bardzo wiele, ale też wiele sobie poukładać i sporo zrozumieć. Sam kurs na doradcę noszenia nie polega wyłącznie na odbiorze, uczestnik ma możliwosc poczuc i zrozumiec, nie tylko istotę noszenia, ale także myslenie i odczuwanie rodzicow, a jesli jest na to otwarty – takze cos w sobie. Zeby nie było zbyt kolorowo – zdjęcie profilowe… widywałam ładniejsze" },
  { name: "Agnieszka Ciupa", title: "Ciągłe doskonalenie", content: "Kurs mam w pamięci do dziś a sposób w jak trenerka Iza przekazuje wiedzę, jej podejście do uczestników sprawia, że nauka jest czystą przyjemnością. Możliwość regularnego kontaktu ze społecznością doradców ClauWi jak również z Izą, którą zapewnia Szkoła ClauWi pozwala na ciągłe doskonalenie swoich umiejętności oraz konsultowanie pojawiających się wątpliwości. Każdemu kto szuka kursu- szczerze polecam! Dziękuję !" },
  { name: "Justyna Starzyk", title: "Rozłożenie wiązań na czynniki pierwsze", content: "Jeśli zastanawiacie się nad kursem na doradcę noszenia, to szczerze polecam wybranie Szkoły Noszenia ClauWi. Podczas kursu można zdobyć wiedzę odnośnie rozwoju fizycznego małego człowieka, korzyściach noszenia czy też zasad prawidłowego i bezpiecznego noszenia. To, co było dla mnie bardzo wartościowe to rozłożenie wiązań na czynniki pierwsze, tak, aby dokładnie zrozumieć ich wpływ na dziecko i na osobę noszącą.Dodam, że Szkoła ClauWi to nie tylko kilkudniowy kurs, to grupa zrzeszająca doradców, na których zawsze można liczyć – wesprą zarówno profesjonalną wiedzą, jak i dobrym słowem. Fajnie znaleźć się w ich gronie" },
  { name: "Anna Kuc", title: "Jako lekarz", content: "Jestem pełna podziwu dla profesjonalizmu szkolenia dla doradców noszenia ClauWi. Jako lekarz zdecydowanie pozytywnie oceniam treści dotyczące rozwoju dziecka i anatomii. Odpowiednio dużo czasu poświęca się też na naukę wiązań. Kończąc kurs doradca jest wyposażony w umiejętności manualne, wiedzę oraz znajomość zasad jak powinna przebiegać dobra konsultacja. Byłam do tej pory uczestniczką licznych kursów na różny temat i niejeden raz miałam poczucie, że temat był ledwie zaczęty, a do wdrożenia do w praktykę jeszcze daleka droga. Tu jest zupełnie inaczej. Doradcy po kursie są gotowi by wyjść ze swoimi umiejętnościami do rodziców chcących nosić dzieci. Jestem również pod wrażeniem prowadzącej Izy Banach-Kubik. Rzadko się spotyka osobę, która potrafi być asertywna, rzeczowa i uprzejma jednocześnie. Polecam kurs gorąco, również profesjonalistom" },
  { name: "Diana Czajczyńska", title: "Nie zawiodłam się", content: "Kurs był pełen rzetelnej wiedzy dotyczącej rozwoju dziecka, każde zagadnienie było dokładnie zobrazowane na modelu kręgosłupa i poparte ćwiczeniami z własnym ciałem, dzięki czemu zdobyłam dużą świadomość zależności w pozycji dziecka i różnic w poszczególnych wiązaniach. Było też dużo praktycznej nauki z chustą, każdy uczestnik miał możliwość dokładnego dopracowania tego, co sprawia mu problem, wiązaliśmy chustę odwołując się zarówno do zdobytej wiedzy i omówienia kroków, jak i wyczucia i pamięci własnego ciała oraz uwagi na jego sygnały. Kurs miał bardzo logiczną strukturę tak, żeby stopniowo zrozumieć coraz większe szczegóły, teraz jako doradca w taki sam przejrzysty sposób tłumaczę rodzicom zagadnienia związane z prawidłowym noszeniem, a do materiałów z kursu zaglądam do dzisiaj. Małe, kameralne grupy oraz bardzo ciepła i wspierająca atmosfera w czasie szkoleń dawały możliwość uczenia się od siebie nawzajem, pomagania i zdobycia wielu cennych rad i opinii nie tylko od trenerów Szkoły, ale także od innych uczestników, często noszących rodziców lub specjalistów w pokrewnych dziedzinach." },
  { name: "Gosia Bukal", title: "Dużo wiedzy i praktyki", content: "Wspaniałe 3 dni szkoleń! Był to bardzo miło spędzony czas z cudowną, pozytywną energia dużo wiedzy teoretycznej jak i praktycznej. Gorąco polecam" },
  { name: "Ola Adamska", title: "W kręgu kobiet", content: "To, co działo się przez te 3 dni to czysta magia. Jestem zaszczycona, że spędziłam ten czas w kręgu kobiet wierzących w to samo w kwestii macierzyństwa. Iza to mega ciepła i empatyczna a zarazem konkretna babka. Życzę sobie, abym szybko mogła powtórzyć to doświadczenie." },
  { name: "Asia Krzywicka", title: "Profesjonalnie i sympatycznie.", content: "Te 3 dni szkoleń to był naprawdę przemiły czas. Zarówno część teoretyczna jak i praktyczna była prowadzona w bardzo profesjonalny sposób, z zachowaniem przy tym bardzo sympatycznej atmosfery. Mam nadzieję, że się jeszcze spotkamy na kursie zaawansowanym." },
  { name: "Paulina Maciaszek", title: "Intensywny kurs", content: "Kurs bardzo intensywny, bogaty w wiedzę, poszerzający kompetencje i umiejętności. Szkolenie ogromnie pomogło mi poukładać sobie wiele rzeczy i zaufać sobie. Cieszę się, że zdecydowałam się na ten krok." },
  { name: "Sylwia Piątkiewicz", title: "Nie tylko JAK ale i PO CO", content: "Brałam udział w kursie podstawowym na doradcę noszenia. Już wcześniej uczyłam się techniki poszczególnych wiązań, miałam parę lat praktyki, ale na kursie nauczyłam się czegoś więcej niż tego “jak”. Teraz wiem dokładnie “po co”Kurs był dla mnie nie tylko możliwością zdobycia nowych kompetencji, ale – jak okazało się w trakcie – chustowymi rekolekcjami (kto bywał na rekolekcjach, ten wie!), ponieważ pomógł mi poukładać wiele rzeczy w głowie, przemyśleć swoje cele związanie z noszeniem i uczeniem noszenia. Nie wspomnę już nawet o tym, że był on dla mnie przydatny osobiście/prywatnie – bo teraz z pełną świadomością noszę swojego malucha.Poza tym – to nie sam kurs, ale osoba prowadząca stanowi o jego jakości i tutaj muszę przyznać, że było to dla mnie wydarzenie nie tylko szkoleniowe, ale ogólnorozwojowe, ponieważ Iza integruje wiedzę z różnych dziedzin i przekazuje ją we wspaniały, spójny sposób swoim kursantom (a atmosfera mega sprzyjająca). Kompleksowa sprawa! Krótko mówiąc – polecam! Gdybym mogła, jutro bym to powtórzyła, dla czystej przyjemności." },
  { name: "Magda Maliniewicz", title: "Pasja", content: "Kurs ClauWi to najlepsza decyzja jaką podjęłam. Niesamowicie aktywnie, miło i przyjemnie spędzony czas. Ogrom wiedzy przekazany w tak ciekawy i zajmujący sposób… . Mam nadzieję, że ta pozytywna energia, którą z taką pasją dzieli się Iza, będzie się we mnie ładnie rozwijać. Było… cudownie! Iza… nadal jestem pod wrażeniem i podoba mi się ten stan! Dziękuję" },
  { name: "Paulina Baranowska", title: "Wyszłam z wiedzą i motywacją", content: "Miałam ogromna przyjemność brać udział w szkoleniu na doradcę noszenia. Było cudownie! Wyszłam z ogromną wiedzą, motywacja i poczuciem że mogę więcej niż mi się wydawało.Kurs daje dużo wiedzy praktycznej ale też mnóstwo teoretycznej, szczególnie ważnej aby móc bezpiecznie nosić maleństwo. Szczerze polecam !" },
  { name: "Dominika Kalkowska", title: "Pełna aktualna wiedza", content: "Po trzech dniach kursant wychodzi z głową pełną aktualnej wiedzy o bezpiecznym noszeniu dzieci w chustach i nosidłach, oraz z powstałą w głowie w trakcie kursu listą nowych pyta na które sam chce szukać odpowiedzi, poprzez aktywne doradztwo i dalsze kształcenie w tym kierunku. Uczestnictwo w szkoleniu na Doradcę noszenia ClauWi, było dla mnie niesamowitym doświadczeniem, mam zaszczyt należeć do tego wyjątkowego grona osób szerzących rodzicielstwo bliskości, poprzez doradztwo. Pięknie dziękuję za tę możliwość i zaufanie." },
  { name: "Weronika Dudek", title: "Stosy chust", content: "Pełen profesjonalizm, ogromna wiedza i bardzo dobry przekaz. Kurs minął w przyjaznej atmosferze. Cudowne stosy chust, materiały szkoleniowe do których wracam z chęcią. Polecam z całego serca!" },
  { name: "Klaudia Balin", title: "Będzie mi brakowało!", content: "Szkolenie było przefantastyczne i aż żal mi że to “tylko” 3 dni bo będzie mi brakowało was wszystkich, wspaniałej atmosfery oraz wykładów i treningu prowadzonych przez Izę która ma wspaniałe zdolności przekazywania wiedzy. Wszystkim mamom, tatusiom oraz pozostałym osobom które się wciąż nie mogą zdecydować serdecznie polecam!" },
  { name: "Aga Szyszka", title: "Więź między uczestnikami", content: "Iza jest otwartą, sympatyczną i ciepłą osobą ,która z niesamowitą łatwością i pełnym zaangażowaniem potrafi przekazać swoim kursantom obszerną wiedzę. Podczas kursu tworzy się między uczestnikami więź i wręcz rodzinna atmosfera, a to wszystko dzięki osobowości Izy. Iza przekazuje nam swoją wiedzę i zaraża nas optymizmem do działania i motywuje nas do pracy. Po zakończeniu kursu aż chce się iść na kolejny by znów móc to przeżyć. Jednak co najważniejsze po ukończonym kursie czuję się dużo bardziej świadoma w temacie zdrowego noszenia dzieci oraz gotowa by szerzyć swoją wiedzę i pomagać innym rodzicom raczkującym w temacie chust czy nosideł. Każdemu kto zastanawia się czy warto wybrać się na kurs odpowiem ,że zdecydowanie ja polecam" },
];
